name: Manually Deploy to Heroku L

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "0b408d00-88af-491b-b39f-cd996b48caae"
          heroku_app_name: "mirror-104-rushi"
          heroku_email: "rushidharlook+2@proton.me"

          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
